/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from "react";
import { AlertOctagon, HelpCircle, FileSignature } from "lucide-react";

export default function DisclaimerView() {
  return (
    <div className="space-y-8 max-w-4xl">
      {/* Header */}
      <div className="space-y-2">
        <h2 className="font-display font-extrabold text-3xl text-text-primary tracking-tight flex items-center gap-3">
          <AlertOctagon className="w-8 h-8 text-amber-500 shrink-0" /> Legal Disclaimer
        </h2>
        <p className="text-text-secondary text-sm">
          Please review the technical application guidelines, limits, and liability terms below.
        </p>
      </div>

      <div className="p-6 rounded-2xl border border-border-main bg-card-bg shadow-sm space-y-6 text-xs text-text-secondary leading-relaxed">
        {/* Section 1 */}
        <div className="space-y-2">
          <h3 className="font-display font-semibold text-text-primary text-sm">
            1. Informational Purposes Only
          </h3>
          <p>
            All conversion algorithms, mathematical ratios, and coefficient outputs generated by UnitConvert are provided strictly for general educational and informational purposes. While every effort has been made to align with the National Institute of Standards and Technology (NIST) Special Publication 811 guides, they are not guaranteed to be 100% error-free.
          </p>
        </div>

        {/* Section 2 */}
        <div className="space-y-2">
          <h3 className="font-display font-semibold text-text-primary text-sm">
            2. High-Risk Applications Exclusion
          </h3>
          <p>
            The software is NOT certified for high-risk applications, including but not limited to medical radiology calibration, aerospace trajectory programming, nuclear physics engineering, high-voltage grid calculations, or structural civil load estimations. Any deployment of these figures in safety-critical systems is done at the absolute risk of the user.
          </p>
        </div>

        {/* Section 3 */}
        <div className="space-y-2">
          <h3 className="font-display font-semibold text-text-primary text-sm">
            3. Limitation of Liability
          </h3>
          <p>
            In no event shall the authors, creators, or hosting partners of UnitConvert be held liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this software, even if advised of the possibility of such damage.
          </p>
        </div>

        {/* Section 4 */}
        <div className="space-y-2">
          <h3 className="font-display font-semibold text-text-primary text-sm flex items-center gap-1.5">
            <FileSignature className="w-4 h-4 text-accent-teal" /> Technical Endorsement
          </h3>
          <p>
            By using this converter platform, you acknowledge that you are responsible for cross-verifying critical numbers against official physical source documents or secondary physical testing machines prior to hardware deployment.
          </p>
        </div>
      </div>
    </div>
  );
}
